# -- 코드를 입력하세요
SELECT 
    D.AUTHOR_ID,
    D.AUTHOR_NAME,
    C.CATEGORY,
    C.TOTAL_SALES
FROM AUTHOR D
JOIN (
    SELECT 
        A.AUTHOR_ID,
        A.CATEGORY,
        SUM(B.SALES * A.PRICE) AS TOTAL_SALES
    FROM BOOK A
    JOIN BOOK_SALES B
        ON A.BOOK_ID = B.BOOK_ID
    WHERE DATE_FORMAT(B.SALES_DATE, '%Y-%m') = '2022-01'
    GROUP BY A.AUTHOR_ID, A.CATEGORY
) C
ON D.AUTHOR_ID = C.AUTHOR_ID
ORDER BY C.AUTHOR_ID ASC, C.CATEGORY DESC;

