-- 코드를 입력하세요
# SELECT A.CAR_ID,
# CASE WHEN A.CAR_ID = B.CAR_ID THEN '대여 가능' 
# ELSE '대여중' END AS 'AVAILABILITY'
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# JOIN (SELECT CAR_ID,
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# HAVING START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16' THEN '대여중'
# ORDER BY CAR_ID DESC AS B) 
# ON A.CAR_ID = B.CAR_ID;

-- 2022-10-16에 대여 중이면 '대여중', 아니면 '대여 가능'
SELECT
  CAR_ID,
  CASE
    WHEN SUM(CASE WHEN DATE('2022-10-16') BETWEEN START_DATE AND END_DATE THEN 1 ELSE 0 END) > 0
      THEN '대여중'
    ELSE '대여 가능'
  END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;

