-- 코드를 작성해주세요
SELECT B.ITEM_ID, B.ITEM_NAME, B.RARITY
FROM ITEM_TREE AS T
JOIN ITEM_INFO A ON A.ITEM_ID = T.PARENT_ITEM_ID
JOIN ITEM_INFO B ON B.ITEM_ID = T.ITEM_ID
WHERE A.RARITY IN ('RARE')
ORDER BY B.ITEM_ID DESC;
