-- 코드를 작성해주세요
# SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE
# FROM ECOLI_DATA AS A
# JOIN ECOLI_DATA AS B
# ON A.ID = B.PARENT_ID
# WHERE A.PARENT_ID & A.ID >= A.PARENT_ID
# ORDER BY A.ID;

SELECT 
    C.ID,
    C.GENOTYPE,
    P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS C
JOIN ECOLI_DATA AS P
  ON C.PARENT_ID = P.ID
WHERE (C.GENOTYPE & P.GENOTYPE) = P.GENOTYPE
ORDER BY C.ID ASC;

