SELECT *
FROM
    (SELECT MONTH(START_DATE) AS MONTH, B.CAR_ID, COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C JOIN
        (SELECT *
        FROM
            (SELECT CAR_ID, COUNT(*) AS CNT
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
            GROUP BY CAR_ID) AS A
        WHERE A.CNT >= 5) AS B
    ON B.CAR_ID = C.CAR_ID
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY MONTH(START_DATE), B.CAR_ID) AS D
WHERE D.RECORDS != 0
ORDER BY MONTH, CAR_ID DESC
;