-- 코드를 작성해주세요
SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM (
    SELECT 
        E.ID,
        E.SIZE_OF_COLONY,
        E.DIFFERENTIATION_DATE,
        M.MAX_SIZE
    FROM ECOLI_DATA E
    JOIN (
        SELECT 
            YEAR(DIFFERENTIATION_DATE) AS YEAR,
            MAX(SIZE_OF_COLONY) AS MAX_SIZE
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) M ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
) AS X
ORDER BY YEAR ASC, YEAR_DEV ASC;
