-- 코드를 작성해주세요
# SELECT A.ID, B.FISH_NAME, A.LENGTH
# FROM FISH_INFO AS A
# JOIN FISH_NAME_INFO AS B
# ON A.FISH_TYPE = B.FISH_TYPE
# WHERE A.LENGTH = 
# ORDER BY A.ID;

SELECT 
    F.ID,
    N.FISH_NAME,
    F.LENGTH
FROM FISH_INFO AS F
JOIN FISH_NAME_INFO AS N
  ON F.FISH_TYPE = N.FISH_TYPE
WHERE (F.FISH_TYPE, F.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    WHERE LENGTH IS NOT NULL
    GROUP BY FISH_TYPE
)
ORDER BY F.ID ASC;

